### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by njnj0314** [nicolasdonati/DUO-FM#1]
Hello, when I run this code, I find that there is no such file as if there is no such file:
sym_dataset

**Comment by nicolasdonati** [comment]
Hi, thanks for the interest,
Sorry you're right you can simply solve this error by eliminating the import of sym_dataset and all its appearances in the train/test code. I can't change the code now I will take care of it in a few days.

**Comment by nicolasdonati** [comment]
The code should now be rid of this sym_dataset error :) I'm closing the issue but feel free to open a new one if a similar problem arises
