### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by SeanSiyang** [nicolasdonati/DUO-FM#2]
Can you provide the download urls of the datasets,like scape、shrec ,and  the directory format of the datasets?

**Comment by SeanSiyang** [comment]
thx

**Comment by nicolasdonati** [comment]
Hi,
I just put the SMAL_r dataset on the repository. You can try things out on this dataset.
I will upload the other datasets shortly :)
thanks for the interest,
ND

**Comment by nicolasdonati** [comment]
Hi again,
I added the anisotropic datasets (FAUST_a and SCAPE_a) in data/
I'm closing the issue but feel free to open a new one if you have any question about the code or data :)
